"""add role_permissions and trusted_assistants tables

Revision ID: 0018
Revises: 0017
Create Date: 2025-01-01 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0018'
down_revision: Union[str, None] = '0017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('permission_id', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_role'), 'role_permissions', ['role'], unique=False)
    
    op.create_table('trusted_assistants',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('teacher_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('assistant_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('can_grade', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'assistant_id', name='uq_teacher_assistant')
    )
    op.create_index(op.f('ix_trusted_assistants_assistant_id'), 'trusted_assistants', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_trusted_assistants_teacher_id'), 'trusted_assistants', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trusted_assistants_teacher_id'), table_name='trusted_assistants')
    op.drop_index(op.f('ix_trusted_assistants_assistant_id'), table_name='trusted_assistants')
    op.drop_table('trusted_assistants')
    op.drop_index(op.f('ix_role_permissions_role'), table_name='role_permissions')
    op.drop_table('role_permissions')
    # ### end Alembic commands ###
