"""add permission_audit table

Revision ID: 0019
Revises: 0018
Create Date: 2025-01-02 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0019'
down_revision: Union[str, None] = '0018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_audit',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('actor_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('target_role', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('permission_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_audit_actor_id'), 'permission_audit', ['actor_id'], unique=False)
    op.create_index(op.f('ix_permission_audit_created_at'), 'permission_audit', ['created_at'], unique=False)
    op.create_index(op.f('ix_permission_audit_target_role'), 'permission_audit', ['target_role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permission_audit_target_role'), table_name='permission_audit')
    op.drop_index(op.f('ix_permission_audit_created_at'), table_name='permission_audit')
    op.drop_index(op.f('ix_permission_audit_actor_id'), table_name='permission_audit')
    op.drop_table('permission_audit')
    # ### end Alembic commands ###
