"""add repository fields (type, language, is_blocked)

Revision ID: 0021
Revises: 0020
Create Date: 2025-01-04 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0021'
down_revision: Union[str, None] = '0020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type
    repository_type = postgresql.ENUM('public', 'private', 'course', name='repository_type')
    repository_type.create(op.get_bind())
    
    # Add columns
    op.add_column('repositories', sa.Column('repo_type', repository_type, nullable=True))
    op.add_column('repositories', sa.Column('language', sa.String(length=50), nullable=True))
    op.add_column('repositories', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    
    # Set defaults for existing rows
    op.execute("UPDATE repositories SET repo_type = 'public', is_blocked = false")
    
    # Make repo_type and is_blocked non-nullable
    op.alter_column('repositories', 'repo_type', nullable=False)
    op.alter_column('repositories', 'is_blocked', nullable=False)
    
    # Create index on repo_type for filtering
    op.create_index(op.f('ix_repositories_repo_type'), 'repositories', ['repo_type'], unique=False)
    op.create_index(op.f('ix_repositories_language'), 'repositories', ['language'], unique=False)
    op.create_index(op.f('ix_repositories_is_blocked'), 'repositories', ['is_blocked'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repositories_is_blocked'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_language'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_repo_type'), table_name='repositories')
    op.drop_column('repositories', 'is_blocked')
    op.drop_column('repositories', 'language')
    op.drop_column('repositories', 'repo_type')
    
    # Drop enum type
    repository_type = postgresql.ENUM('public', 'private', 'course', name='repository_type')
    repository_type.drop(op.get_bind())
    # ### end Alembic commands ###
